org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

version=0.1.0
versioning.stage=alpha

POM_INCEPTION_YEAR=2026
POM_URL=https://github.com/Rongmario/FormatJ
POM_SCM_URL=https://github.com/Rongmario/FormatJ
POM_SCM_CONNECTION=scm:git:git://github.com/Rongmario/FormatJ.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/Rongmario/FormatJ.git
POM_DEVELOPER_ID=Rongmario
POM_DEVELOPER_NAME=Rongmario
POM_DEVELOPER_URL=https://github.com/Rongmario
